---
- name: Set BPM Suite Artifact Facts
  set_fact:
    jboss_bxms_artifact_tmp_dest: "{{ '/tmp/' + jboss_bxms_artifact_name }}"
    jboss_bxms_business_central_location: "{{ jboss_bxms_deployment_directory + '/business-central.war' }}"
    jboss_bxms_dashbuilder_location: "{{ jboss_bxms_deployment_directory + '/dashbuilder.war' }}"
    jboss_bxms_kie_server_location: "{{ jboss_bxms_deployment_directory + '/kie-server.war' }}"

- include: check_for_bxms_install.yml

- name: Copy JBoss BxMS
  copy:
    src: "{{ jboss_bxms_artifact_name }}"
    dest: "{{ jboss_bxms_artifact_tmp_dest }}"
  when: transfer_method == 'copy-from-controller' and jboss_bxms_exists == false

- name: Async Download JBoss BxMS from Red Hat Customer Portal
  redhat_csp_download:
    url: "{{ jboss_bxms_artifact_source }}"
    dest: "{{ jboss_bxms_artifact_tmp_dest }}"
    username: "{{ rhn_username }}"
    password: "{{ rhn_password }}"
  async: 7200
  poll: 0
  register: jboss_bxms_download
  when: transfer_method == 'csp-to-host' and jboss_bxms_exists == false

- name: 'Check On JBoss BxMS Download Completion'
  async_status: jid={{ jboss_bxms_download.ansible_job_id }}
  register: job_result3
  until: job_result3.finished
  retries: 600
  delay: 10
  when: transfer_method == 'csp-to-host' and jboss_bxms_exists == false

# This is a hack for service naming differences in RHEL 6 vs 7
- block:
  - name: Stop BxMS Service
    service:
      name: "{{ jboss_bxms_service_name }}"
      state: stopped
    when: jboss_bxms_exists == false

  rescue:
  - name: Stop BxMS Service With .sh
    service:
      name: "{{ jboss_bxms_service_name }}.sh"
      state: stopped
    when: jboss_bxms_exists == false

# For EAP, this should overlay the BPM download over EAP, intentionally overwriting some files in the process
- name: Extract BPM Suite
  become: true
  unarchive:
    src: "{{ jboss_bxms_artifact_tmp_dest }}"
    dest: "{{ jboss_bxms_artifact_dest }}"
    copy: no
    owner: "{{ jboss_bxms_service_user }}"
    group: "{{ jboss_bxms_service_group }}"
  when: jboss_bxms_exists == false

- name: Remove Business Central WAR
  file:
    state: absent
    path: "{{ jboss_bxms_business_central_location }}"
  when: jboss_bxms_deploy_business_central == false

- name: Remove Business Central Deployment Marker
  file:
    state: absent
    path: "{{ jboss_bxms_business_central_location + '.dodeploy' }}"
  when: jboss_bxms_deploy_business_central == false

- name: Remove Dashbuilder WAR
  file:
    state: absent
    path: "{{ jboss_bxms_dashbuilder_location }}"
  when: jboss_bxms_deploy_dashbuilder == false

- name: Remove Dashbuilder Deployment Marker
  file:
    state: absent
    path: "{{ jboss_bxms_dashbuilder_location + '.dodeploy' }}"
  when: jboss_bxms_deploy_dashbuilder == false

- name: Remove KIE Server WAR
  file:
    state: absent
    path: "{{ jboss_bxms_kie_server_location }}"
  when: jboss_bxms_deploy_kie_server == false

- name: Remove KIE Server Deployment Marker
  file:
    state: absent
    path: "{{ jboss_bxms_kie_server_location + '.dodeploy' }}"
  when: jboss_bxms_deploy_kie_server == false

- include: configuration_files.yml

- include: java_opts.yml
